version: 0.2

phases:
  install:
    commands:
      - echo install node
      - curl -sL https://deb.nodesource.com/setup_12.x | -E bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo install dependencies
      - npm install
  build:
    commands:
      # tests
      - echo building
      - npm build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist
